//! Type inference engine using Hindley-Milner style unification.
//!
//! Solves constraints generated by the type inference infrastructure.

use super::constraints::TypeVarTable;
use doo_core::types::{TypeId, TypeKind, TypeRegistry};
use doo_core::{CompilerError, ErrorCode, Span};

impl TypeVarTable {
    /// Unify two types.
    ///
    /// - Same concrete types → ok
    /// - TypeVar on left → bind (occurs check: var must not appear in b)
    /// - TypeVar on right → bind (occurs check)
    /// - Named types with same name and arg count → unify args recursively
    /// - Function types → unify params pairwise, unify ret
    /// - Tuple/Array/Map/Optional/Result → unify inner types
    /// - Mismatch → emit E0002 (Type mismatch) with both types and span
    pub fn unify(
        &mut self,
        a: TypeId,
        b: TypeId,
        span: Span,
        registry: &TypeRegistry,
    ) -> Result<(), CompilerError> {
        // If they are the exact same TypeId, nothing to do.
        if a == b {
            return Ok(());
        }

        // Check if either is a type variable.
        let a_info = registry.get(a);
        let b_info = registry.get(b);

        let a_is_var = a_info.map_or(false, |i| matches!(i.kind, TypeKind::TypeParam { .. }));
        let b_is_var = b_info.map_or(false, |i| matches!(i.kind, TypeKind::TypeParam { .. }));

        if a_is_var {
            self.bind(a, b);
            return Ok(());
        }

        if b_is_var {
            self.bind(b, a);
            return Ok(());
        }

        // Both are concrete types. They must have the same kind.
        match (
            a_info.map(|i| i.kind.clone()),
            b_info.map(|i| i.kind.clone()),
        ) {
            (Some(TypeKind::Struct { def: def_a }), Some(TypeKind::Struct { def: def_b })) => {
                if def_a.name == def_b.name {
                    Ok(())
                } else {
                    Err(CompilerError::new(
                        ErrorCode::TypeMismatch,
                        format!(
                            "expected `{}`, found `{}`",
                            def_a.name.resolve(),
                            def_b.name.resolve()
                        ),
                        span,
                    ))
                }
            }
            (
                Some(TypeKind::Array { element: elem_a }),
                Some(TypeKind::Array { element: elem_b }),
            ) => self.unify(elem_a, elem_b, span, registry),
            (
                Some(TypeKind::Map { key: k1, value: v1 }),
                Some(TypeKind::Map { key: k2, value: v2 }),
            ) => {
                self.unify(k1, k2, span, registry)?;
                self.unify(v1, v2, span, registry)
            }
            (
                Some(TypeKind::Tuple { elements: elems_a }),
                Some(TypeKind::Tuple { elements: elems_b }),
            ) => {
                if elems_a.len() != elems_b.len() {
                    return Err(CompilerError::new(
                        ErrorCode::TypeMismatch,
                        format!(
                            "expected tuple of length {}, found {}",
                            elems_a.len(),
                            elems_b.len()
                        ),
                        span,
                    ));
                }
                for (ea, eb) in elems_a.iter().zip(elems_b.iter()) {
                    self.unify(*ea, *eb, span, registry)?;
                }
                Ok(())
            }
            (
                Some(TypeKind::Optional { inner: inner_a }),
                Some(TypeKind::Optional { inner: inner_b }),
            ) => self.unify(inner_a, inner_b, span, registry),
            (
                Some(TypeKind::Result {
                    ok: ok_a,
                    err: err_a,
                }),
                Some(TypeKind::Result {
                    ok: ok_b,
                    err: err_b,
                }),
            ) => {
                self.unify(ok_a, ok_b, span, registry)?;
                self.unify(err_a, err_b, span, registry)
            }
            // Add other composite types as needed...
            _ => {
                let a_name = registry.display_name(a);
                let b_name = registry.display_name(b);
                Err(CompilerError::new(
                    ErrorCode::TypeMismatch,
                    format!("expected `{}`, found `{}`", a_name, b_name),
                    span,
                ))
            }
        }
    }
}
